#!/usr/bin/perl

#this just places traceR in the /usr/bin directory
#make sure to chmod +x this file before using the script

use strict;
use warnings;

sub main {
   system "make";
   system "sudo cp traceR /usr/bin/";
   system "make clean";
}

main ();
